instance cdk

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -56,6 +56,10 @@ jobs:
             export $s
           done
           wait-on "http://$PublicDNS" -t 180000 -i 10000 -v
+          if [ $? == 1 ]; then
+            echo "Waiting failed -> exit 1"
+            exit 1
+          fi
           yes | cdk destroy "$STACK_NAME"
     - stage: Deploy Test
       name: Deploy Parent
