test alf reachable

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -72,10 +72,10 @@ jobs:
         - SERVER=$(./node_modules/node-jq/bin/jq -r '.values[] | select(.key=="url").value' tmp/newman/global-vars.json)
         - echo "Server = $SERVER"
         - ./node_modules/wait-on/bin/wait-on "http-get://$SERVER" -t 50000 -i 10000 -v
-        - if [ $? == 1 ]; then
-            echo "Waiting failed -> exit 1"
-            exit 1
-          fi
+        # - if [ $? == 1 ]; then
+        #     echo "Waiting failed -> exit 1"
+        #     exit 1
+        #   fi
         - aws logs get-log-events --log-group-name $LG_NAME --log-stream-name $LG_STREAM_NAME
 
 after_failure:
