swift production to my account

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -78,25 +78,26 @@ jobs:
         # - export WITH_SWAGGER='false' && cdk bootstrap "aws://$AWS_ACCOUNT_NUMBER/$CDK_DEFAULT_REGION"
         - STACK_NAME=AlfInstancesStackEuWest2
         - STACK_NAME_P=AlfInstancesStackEuWest2Prod
-        - npm run build
-        - |
-          if ${destroyBefore} ; then
-            export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME"
-            if ${updateProduction} ; then
-              export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME_P" --profile=prod
-            fi
-          fi
-        - |
-          if ! ${deploy} ; then
-            echo 'abort deploying as deploy == false';
-            travis_terminate 0
-          fi
-        - export $CI_USER_TOKEN
-        - |
-          export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME" --require-approval never
-          if ${updateProduction} ; then
-            export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME_P" --profile=prod --require-approval never
-          fi
+        # - npm run build
+        # - |
+        #   if ${destroyBefore} ; then
+        #     export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME"
+        #     if ${updateProduction} ; then
+        #       export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME_P" --profile=prod
+        #     fi
+        #   fi
+        # - |
+        #   if ! ${deploy} ; then
+        #     echo 'abort deploying as deploy == false';
+        #     travis_terminate 0
+        #   fi
+        # - export $CI_USER_TOKEN
+        # - |
+        #   export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME" --require-approval never
+        #   if ${updateProduction} ; then
+        #     export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME_P" --profile=prod --require-approval never
+        #   fi
+        - cat ~/.aws/config
         - OUTPUTS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs" --output json )
         - |
           for s in $(echo $OUTPUTS | ./node_modules/node-jq/bin/jq -r '.[] | "\(.OutputKey)=\(.OutputValue)"'); do
