cors again ...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -34,8 +34,8 @@ stages:
 
 env:
   destroyBefore: false
-  deploy: true
-  updateProduction: true
+  deployTest: false
+  deployProd: true
   destroyAfter: false
 
 jobs:
@@ -56,20 +56,22 @@ jobs:
         - |
           if ${destroyBefore} ; then
             export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME" > /dev/null
-            if ${updateProduction} ; then
+            if ${deployProd} ; then
               export WITH_SWAGGER='false' && yes | cdk destroy "$STACK_NAME_P" --profile=prod > /dev/null
             fi
           fi
-        - |
-          if ! ${deploy} ; then
-            echo 'abort deploying as deploy == false';
-            travis_terminate 0
-          fi
+        # - |
+        #   if ! ${deploy} ; then
+        #     echo 'abort deploying as deploy == false';
+        #     travis_terminate 0
+        #   fi
         - export $CI_USER_TOKEN
         - "travis_wait 30 sleep 1800 &"
         - |
-          export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME" --require-approval never  > /dev/null
-          if ${updateProduction} ; then
+          if ${deployTest} ; then
+            export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME" --require-approval never  > /dev/null
+          fi
+          if ${deployProd} ; then
             export WITH_SWAGGER='false' && yes | cdk deploy "$STACK_NAME_P" --profile=prod --require-approval never  > /dev/null
           fi
         - OUTPUTS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs" --output json )
@@ -97,8 +99,10 @@ jobs:
         - npm run build
         - "travis_wait 30 sleep 1800 &"
         - |
-          export WITH_SWAGGER='true' && yes | cdk deploy "$STACK_NAME" --require-approval never  > /dev/null
-          if ${updateProduction} ; then
+          if ${deployTest} ; then
+            export WITH_SWAGGER='true' && yes | cdk deploy "$STACK_NAME" --require-approval never  > /dev/null
+          fi
+          if ${deployProd} ; then
             export WITH_SWAGGER='true' && yes | cdk deploy "$STACK_NAME_P" --profile=prod --require-approval never  > /dev/null
           fi
         - aws apigateway create-deployment --rest-api-id $RestApiId --stage-name prod
